version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "firstslambda"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1bos5x24ejk9j"
s3_prefix = "firstslambda"
region = "us-east-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
